version: '3'
services:
  nginx:
    image: nginx:1.17
    networks:
      - front
      - middle
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - src:/app/public:ro

  app:
    image: laravel7:latest
    build: .
    networks:
      - middle
      - back
    volumes:
      - ./docker/.env:/app/.env
      - src:/app/public

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - back
    volumes:
      - data:/var/lib/mysql

networks:
  front:
  middle:
  back:

volumes:
  src:
  data:
